### ISSUE TITLE
User Services

### ISSUE THREAD

**Issue by magnojunior07** [mardenrafael/contaboi-backend#12]
# Todo list
- [x] Get User Service
- [x] Create User Service
- [x] Update User Service
- [x] Delete User Service
