### ISSUE TITLE
User Controllers

### ISSUE THREAD

**Issue by magnojunior07** [mardenrafael/contaboi-backend#13]
# Todo list
- [x] Get User Controller
- [x] Create User Controller
- [x] Update User Controller
- [x] Delete User Controller
