### ISSUE TITLE
Ox services

### ISSUE THREAD

**Issue by mardenrafael** [mardenrafael/contaboi-backend#5]
# Todo list
- [x] Get Ox Service
- [x] Create Ox Service
- [x] Update Ox Service
- [x] Delete Ox Service
