### ISSUE TITLE
Ox Controllers

### ISSUE THREAD

**Issue by magnojunior07** [mardenrafael/contaboi-backend#7]
# Todo list
- [x] Get Ox Controller
- [x] Create Ox Controller
- [x] Update Ox Controller
- [x] Delete Ox Controller
